export const categories = [
  { id: 1, name: "Plumbing", serviceName: "Plumbing", icon: "water" },
  { id: 2, name: "Electrician", serviceName: "Electrician", icon: "flash" },
  { id: 3, name: "Carpenter", serviceName: "Carpenter", icon: "hammer" },
  { id: 4, name: "Painter", serviceName: "Painter", icon: "color-fill" },
  { id: 5, name: "Cleaning", serviceName: "Cleaning", icon: "sparkles" },
  { id: 6, name: "Pest Control", serviceName: "Pest Control", icon: "bug" },
  { id: 7, name: "Appliance Repair", serviceName: "Appliance Repair", icon: "construct" },
  { id: 8, name: "Home Salon", serviceName: "Home Salon", icon: "cut" },
  { id: 9, name: "Gardening", serviceName: "Gardening", icon: "leaf" },
  { id: 10, name: "Car Wash", serviceName: "Car Wash", icon: "car" },
  { id: 11, name: "AC Repair", serviceName: "AC Repair", icon: "snow" },
  { id: 12, name: "Mobile Repair", serviceName: "Mobile Repair", icon: "phone-portrait" },
  { id: 13, name: "Computer Repair", serviceName: "Computer Repair", icon: "desktop" },
  { id: 14, name: "Tutor", serviceName: "Tutor", icon: "school" },
  { id: 15, name: "Yoga Trainer", serviceName: "Yoga Trainer", icon: "fitness" },
  { id: 16, name: "Laundry", serviceName: "Laundry", icon: "shirt" },
  { id: 17, name: "Tailor", serviceName: "Tailor", icon: "scissors" },
  { id: 18, name: "Barber", serviceName: "Barber", icon: "cut" },
  { id: 19, name: "Cook", serviceName: "Cook", icon: "restaurant" },
  { id: 20, name: "Photography", serviceName: "Photography", icon: "camera" },
  { id: 21, name: "Event Management", serviceName: "Event Management", icon: "calendar" },
  { id: 22, name: "Florist", serviceName: "Florist", icon: "flower" },
  { id: 23, name: "Courier Service", serviceName: "Courier Service", icon: "paper-plane" },
  { id: 24, name: "Security Guard", serviceName: "Security Guard", icon: "shield" },
  { id: 25, name: "Driver", serviceName: "Driver", icon: "car" },
];